amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.5
    alpha2: 0.5
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.2
    do_beamskip: True
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 4.0
    laser_max_range: 5.0
    laser_min_range: 0.2
    laser_model_type: "likelihood_field"
    max_beams: 180
    max_particles: 5000
    min_particles: 700
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.00005
    recovery_alpha_slow: 0.00005
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 1.0
    sigma_hit: 0.2
    tf_broadcast: True
    transform_tolerance: 1.5
    update_min_a: 0.08
    update_min_d: 0.08
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan
    set_initial_pose: True
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_z: 0.0
    initial_pose_yaw: 0.0
amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    enable_groot_monitoring: True
    groot_zmq_publisher_port: 1666
    groot_zmq_server_port: 1667
    transform_tolerance: 2.0
    default_bt_xml_filename: "/home/nuc/ws/src/AR_HT_01/AR_HT_navigation/behaivor_trees/navigate_w_replanning_and_recovery.xml"
    goal_reached_tol: 0.3
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_truncate_path_action_bt_node
    - nav2_goal_updater_node_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

# controller_server:
#   ros__parameters:
#     use_sim_time: True
#     ontroller_frequency: 20.0
#     min_x_velocity_threshold: 0.001
#     min_y_velocity_threshold: 0.5
#     min_theta_velocity_threshold: 0.001
#     progress_checker_plugin: "progress_checker"
#     goal_checker_plugin: "goal_checker"
#     controller_plugins: ["FollowPath"]
#     # Progress checker parameters
#     progress_checker:
#       plugin: "nav2_controller::SimpleProgressChecker"
#       required_movement_radius: 0.25
#       movement_time_allowance: 10.0
#     # Goal checker parameters
#     goal_checker:
#       plugin: "nav2_controller::SimpleGoalChecker"
#       xy_goal_tolerance: 0.25
#       yaw_goal_tolerance: 0.25
#       stateful: True
#     # TEB parameters
#     FollowPath:
#       plugin: "teb_local_planner::TebLocalPlannerROS"
#       odom_topic: "odom"
#       # Trajectory
#       teb_autosize: 1.0
#       teb_autoresize: True
#       dt_ref: 0.3
#       dt_hysteresis: 0.1
#       max_samples: 500
#       global_plan_overwrite_orientation: True
#       allow_init_with_backwards_motion: False
#       max_global_plan_lookahead_dist: 3.0
#       global_plan_viapoint_sep: -1.0
#       global_plan_prune_distance: 1.0
#       exact_arc_length: False
#       feasibility_check_no_poses: 5
#       publish_feedback: False
#       # Robot
              
#       max_vel_x: 0.22
#       max_vel_x_backwards: 0.22
#       max_vel_y: 0.0
#       max_vel_theta: 1.0
#       acc_lim_x: 0.5
#       acc_lim_theta: 0.5
#       min_turning_radius: 0.0 # diff-drive robot (can turn on place!)
#       footprint_model:
#         type: "point"

#       # GoalTolerance
          
#       xy_goal_tolerance: 0.2
#       yaw_goal_tolerance: 0.1
#       free_goal_vel: False
#       complete_global_plan: True
          
#       # Obstacles
          
#       min_obstacle_dist: 0.08 # This value must also include our robot radius, since footprint_model is set to "point".
#       inflation_dist: 0.08
#       include_costmap_obstacles: True
#       costmap_obstacles_behind_robot_dist: 1.0
#       obstacle_poses_affected: 25

#       dynamic_obstacle_inflation_dist: 0.3
#       include_dynamic_obstacles: True

#       costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
#       costmap_converter_spin_thread: True
#       costmap_converter_rate: 10
      
#       # Optimization
          
#       no_inner_iterations: 5
#       no_outer_iterations: 4
#       optimization_activate: True
#       optimization_verbose: False
#       penalty_epsilon: 0.1
#       obstacle_cost_exponent: 4.0
#       weight_max_vel_x: 2.0
#       weight_max_vel_theta: 1.0
#       weight_acc_lim_x: 1.0
#       weight_acc_lim_theta: 1.0
#       weight_kinematics_nh: 1000.0
#       weight_kinematics_forward_drive: 1.0
#       weight_kinematics_turning_radius: 1.0
#       weight_optimaltime: 1.0 # must be > 0
#       weight_shortest_path: 0.0
#       weight_obstacle: 100.0
#       weight_inflation: 0.2
#       weight_dynamic_obstacle: 10.0
#       weight_dynamic_obstacle_inflation: 0.2
#       weight_viapoint: 1.0
#       weight_adapt_factor: 2.0

#       # Homotopy Class Planner

#       enable_homotopy_class_planning: True
#       enable_multithreading: True
#       max_number_classes: 4
#       selection_cost_hysteresis: 1.0
#       selection_prefer_initial_plan: 0.9
#       selection_obst_cost_scale: 100.0
#       selection_alternative_time_cost: False
      
#       roadmap_graph_no_samples: 15
#       roadmap_graph_area_width: 5.0
#       roadmap_graph_area_length_scale: 1.0
#       h_signature_prescaler: 0.5
#       h_signature_threshold: 0.1
#       obstacle_heading_threshold: 0.45
#       switching_blocking_period: 0.0
#       viapoints_all_candidates: True
#       delete_detours_backwards: True
#       max_ratio_detours_duration_best_duration: 3.0
#       visualize_hc_graph: False
#       visualize_with_time_as_z_axis_scale: -1.0

#       # Recovery
      
#       shrink_horizon_backup: True
#       shrink_horizon_min_duration: 10.0
#       oscillation_recovery: True
#       oscillation_v_eps: 0.1
#       oscillation_omega_eps: 0.1
#       oscillation_recovery_min_duration: 10.0
#       oscillation_filter_duration: 10.0
      
#     costmap_converter:
#       ros__parameters:
#         use_sim_time: True
controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.1
    min_theta_velocity_threshold: 0.01
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]

    # Progress checker parameters
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.4
      movement_time_allowance: 20.0
    # Goal checker parameters
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.25
      yaw_goal_tolerance: 0.35
      stateful: True
    # DWB parameters
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: True
      min_vel_x: -0.23
      min_vel_y: 0.0
      max_vel_x: 0.23
      max_vel_y: 0.0
      max_vel_theta: 0.6
      min_speed_xy: 0.0
      max_speed_xy: 0.23
      min_speed_theta: -0.6
      # Add high threshold velocity for turtlebot 3 issue.
      # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
      acc_lim_x: 2.0
      acc_lim_y: 0.0
      acc_lim_theta: 2.0
      decel_lim_x: -2.0
      decel_lim_y: 0.0
      decel_lim_theta: -2.0
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 50
      sim_time: 2.0
      linear_granularity: 0.15
      angular_granularity: 0.15
      transform_tolerance: 2.0
      xy_goal_tolerance: 0.3
      trans_stopped_velocity: 0.0
      short_circuit_trajectory_evaluation: True
      stateful: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.05
      PathAlign.scale: 0.0
      #PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 0.0
      #GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 0.1
      RotateToGoal.lookahead_time: -1.0
      # # critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      # BaseObstacle.scale: 0.02
      # PathAlign.scale: 32.0
      # GoalAlign.scale: 32.0
      # Oscillation.scale: 30.0
      # # PathAlign.forward_point_distance: 0.5
      # # GoalAlign.forward_point_distance: 0.5
      # PathDist.scale: 128.0
      # GoalDist.scale: 32.0
      # RotateToGoal.scale: 10.0
      # RotateToGoal.slowing_factor: 5.0
      # RotateToGoal.lookahead_time: -1.0
controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 15.0
      publish_frequency: 15.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      footprint: "[[0.17, 0.25], [0.17, -0.25], [-0.38, -0.25], [-0.38, 0.25]]"
      # robot_radius: 0.25
      plugins: ["voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.58
        inflation_radius: 1.5
      voxel_layer:
        plugin: "nav2_costmap_2d::VoxelLayer"
        enabled: True
        publish_voxel_map: True
        origin_z: 0.0
        z_resolution: 0.05
        z_voxels: 16
        max_obstacle_height: 2.0
        mark_threshold: 0
        observation_sources: "scan_hls"
        
        scan_hls:
          topic: /scan
          max_obstacle_height: 5.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True

global_costmap:
  global_costmap:
    ros__parameters:
      width: 10  
      height: 10 
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      # robot_radius: 0.22
      footprint: "[[0.17, 0.25], [0.17, -0.25], [-0.38, -0.25], [-0.38, 0.25]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      # plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan_1
        scan:
          topic: /scan
          max_obstacle_height: 5.0
          clearing: True
          marking: True
          data_type: "LaserScan"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 2.58
        inflation_radius: 1.5
      always_send_full_costmap: True
      
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "turtlebot3_world.yaml"

map_saver:
  ros__parameters:
    use_sim_time: True
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

planner_server:
  ros__parameters:
    expected_planner_frequency: 10.0
    use_sim_time: True
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

recoveries_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 5.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 2.0
    use_sim_time: true
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.4
    min_rotational_vel: 0.2
    rotational_acc_lim: 0.5

robot_state_publisher:
  ros__parameters:
    use_sim_time: True

waypoint_follower:
  ros__parameters:
    loop_rate: 10
    stop_on_failure: false
    waypoint_task_executor_plugin: "wait_at_waypoint"   
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200